// 种子数据：常见药物
export const seedDrugs = [
  {
    name: '阿司匹林',
    genericName: 'Aspirin',
    description: '非甾体抗炎药，用于缓解疼痛、发热和炎症，也用于预防心血管疾病',
    category: '解热镇痛药',
    sideEffects: ['胃肠道不适', '出血风险增加', '过敏反应'],
    contraindications: ['活动性消化道溃疡', '严重肝肾功能不全', '血友病'],
    dosage: '成人：每次300-600mg，每日3-4次，饭后服用',
    source: 'manual',
  },
  {
    name: '布洛芬',
    genericName: 'Ibuprofen',
    description: '非甾体抗炎药，用于缓解轻至中度疼痛、发热和炎症',
    category: '解热镇痛药',
    sideEffects: ['胃肠道不适', '头痛', '眩晕'],
    contraindications: ['消化道溃疡', '严重心功能不全', '孕晚期'],
    dosage: '成人：每次200-400mg，每日3-4次，饭后服用',
    source: 'manual',
  },
  {
    name: '对乙酰氨基酚',
    genericName: 'Paracetamol',
    description: '解热镇痛药，用于缓解轻至中度疼痛和发热',
    category: '解热镇痛药',
    sideEffects: ['肝损伤（过量时）', '皮疹', '恶心'],
    contraindications: ['严重肝功能不全', '对本品过敏'],
    dosage: '成人：每次500mg，每日3-4次，最大剂量4g/日',
    source: 'manual',
  },
  {
    name: '阿莫西林',
    genericName: 'Amoxicillin',
    description: '青霉素类抗生素，用于治疗细菌感染',
    category: '抗生素',
    sideEffects: ['过敏反应', '腹泻', '恶心'],
    contraindications: ['青霉素过敏', '传染性单核细胞增多症'],
    dosage: '成人：每次500mg，每日3次，饭后服用',
    source: 'manual',
  },
  {
    name: '头孢克肟',
    genericName: 'Cefixime',
    description: '第三代头孢菌素类抗生素，用于治疗呼吸道、泌尿道等感染',
    category: '抗生素',
    sideEffects: ['腹泻', '恶心', '皮疹'],
    contraindications: ['头孢菌素过敏'],
    dosage: '成人：每次200mg，每日2次',
    source: 'manual',
  },
  {
    name: '氨氯地平',
    genericName: 'Amlodipine',
    description: '钙通道阻滞剂，用于治疗高血压和心绞痛',
    category: '降压药',
    sideEffects: ['头痛', '水肿', '面部潮红'],
    contraindications: ['严重低血压', '主动脉瓣狭窄'],
    dosage: '成人：每日5-10mg，一次服用',
    source: 'manual',
  },
  {
    name: '硝苯地平',
    genericName: 'Nifedipine',
    description: '钙通道阻滞剂，用于治疗高血压和心绞痛',
    category: '降压药',
    sideEffects: ['头痛', '面部潮红', '心悸'],
    contraindications: ['严重低血压', '急性心肌梗死'],
    dosage: '成人：每次10-20mg，每日3次',
    source: 'manual',
  },
  {
    name: '美托洛尔',
    genericName: 'Metoprolol',
    description: 'β受体阻滞剂，用于治疗高血压、心绞痛和心律失常',
    category: '降压药',
    sideEffects: ['疲劳', '头晕', '心动过缓'],
    contraindications: ['严重心动过缓', '心源性休克', '支气管哮喘'],
    dosage: '成人：每次50-100mg，每日2次',
    source: 'manual',
  },
  {
    name: '二甲双胍',
    genericName: 'Metformin',
    description: '双胍类降糖药，用于治疗2型糖尿病',
    category: '降糖药',
    sideEffects: ['胃肠道不适', '腹泻', '乳酸酸中毒（罕见）'],
    contraindications: ['严重肾功能不全', '酮症酸中毒', '严重感染'],
    dosage: '成人：起始剂量500mg，每日2-3次，饭后服用',
    source: 'manual',
  },
  {
    name: '格列美脲',
    genericName: 'Glimepiride',
    description: '磺脲类降糖药，用于治疗2型糖尿病',
    category: '降糖药',
    sideEffects: ['低血糖', '体重增加', '恶心'],
    contraindications: ['1型糖尿病', '糖尿病酮症酸中毒', '严重肝肾功能不全'],
    dosage: '成人：起始剂量1mg，每日1次，早餐前服用',
    source: 'manual',
  },
  {
    name: '奥美拉唑',
    genericName: 'Omeprazole',
    description: '质子泵抑制剂，用于治疗胃溃疡、十二指肠溃疡和胃食管反流病',
    category: '消化系统药物',
    sideEffects: ['头痛', '腹泻', '恶心'],
    contraindications: ['对本品过敏'],
    dosage: '成人：每次20mg，每日1-2次，饭前服用',
    source: 'manual',
  },
  {
    name: '雷尼替丁',
    genericName: 'Ranitidine',
    description: 'H2受体拮抗剂，用于治疗消化性溃疡和胃食管反流病',
    category: '消化系统药物',
    sideEffects: ['头痛', '便秘', '腹泻'],
    contraindications: ['对本品过敏'],
    dosage: '成人：每次150mg，每日2次',
    source: 'manual',
  },
  {
    name: '氯雷他定',
    genericName: 'Loratadine',
    description: '第二代抗组胺药，用于治疗过敏性鼻炎和荨麻疹',
    category: '抗过敏药',
    sideEffects: ['头痛', '嗜睡（轻微）', '口干'],
    contraindications: ['对本品过敏'],
    dosage: '成人：每日10mg，一次服用',
    source: 'manual',
  },
  {
    name: '西替利嗪',
    genericName: 'Cetirizine',
    description: '第二代抗组胺药，用于治疗过敏性鼻炎和荨麻疹',
    category: '抗过敏药',
    sideEffects: ['嗜睡', '头痛', '口干'],
    contraindications: ['对本品过敏', '严重肾功能不全'],
    dosage: '成人：每日10mg，一次服用',
    source: 'manual',
  },
  {
    name: '辛伐他汀',
    genericName: 'Simvastatin',
    description: '他汀类降脂药，用于治疗高胆固醇血症',
    category: '调脂药',
    sideEffects: ['肌肉疼痛', '肝酶升高', '头痛'],
    contraindications: ['活动性肝病', '妊娠期', '哺乳期'],
    dosage: '成人：每日10-40mg，晚上服用',
    source: 'manual',
  },
  {
    name: '阿托伐他汀',
    genericName: 'Atorvastatin',
    description: '他汀类降脂药，用于治疗高胆固醇血症和预防心血管疾病',
    category: '调脂药',
    sideEffects: ['肌肉疼痛', '肝酶升高', '消化不良'],
    contraindications: ['活动性肝病', '妊娠期', '哺乳期'],
    dosage: '成人：每日10-80mg，一次服用',
    source: 'manual',
  },
  {
    name: '华法林',
    genericName: 'Warfarin',
    description: '抗凝血药，用于预防和治疗血栓栓塞性疾病',
    category: '抗凝药',
    sideEffects: ['出血', '皮疹', '脱发'],
    contraindications: ['活动性出血', '严重肝肾功能不全', '妊娠期'],
    dosage: '成人：根据INR值调整，通常2-10mg/日',
    source: 'manual',
  },
  {
    name: '氯吡格雷',
    genericName: 'Clopidogrel',
    description: '抗血小板药，用于预防动脉粥样硬化血栓形成',
    category: '抗凝药',
    sideEffects: ['出血', '皮疹', '腹泻'],
    contraindications: ['活动性出血', '严重肝功能不全'],
    dosage: '成人：每日75mg，一次服用',
    source: 'manual',
  },
  {
    name: '地西泮',
    genericName: 'Diazepam',
    description: '苯二氮䓬类药物，用于抗焦虑、镇静催眠和抗惊厥',
    category: '镇静催眠药',
    sideEffects: ['嗜睡', '头晕', '依赖性'],
    contraindications: ['重症肌无力', '急性闭角型青光眼', '严重呼吸功能不全'],
    dosage: '成人：每次2.5-10mg，每日2-3次',
    source: 'manual',
  },
  {
    name: '艾司唑仑',
    genericName: 'Estazolam',
    description: '苯二氮䓬类药物，用于失眠症的短期治疗',
    category: '镇静催眠药',
    sideEffects: ['嗜睡', '头晕', '依赖性'],
    contraindications: ['重症肌无力', '急性闭角型青光眼', '严重呼吸功能不全'],
    dosage: '成人：睡前1-2mg',
    source: 'manual',
  },
]
