// 种子数据：常见药物相互作用
// 注意：这些数据将在导入时与实际的药物ID关联
export const seedInteractions = [
  {
    drug1Name: '阿司匹林',
    drug2Name: '华法林',
    interactionType: '药效增强',
    severity: 'high',
    description: '阿司匹林与华法林联用会显著增加出血风险，两者都具有抗凝血作用',
    recommendation: '避免联用，如必须使用需密切监测INR值和出血症状',
    source: 'database',
  },
  {
    drug1Name: '阿司匹林',
    drug2Name: '布洛芬',
    interactionType: '药效减弱',
    severity: 'medium',
    description: '布洛芬可能降低阿司匹林的心血管保护作用',
    recommendation: '如需联用，建议先服用阿司匹林，至少间隔2小时后再服用布洛芬',
    source: 'database',
  },
  {
    drug1Name: '阿司匹林',
    drug2Name: '氯吡格雷',
    interactionType: '药效增强',
    severity: 'high',
    description: '两种抗血小板药物联用会显著增加出血风险',
    recommendation: '仅在医生指导下联用，需密切监测出血症状',
    source: 'database',
  },
  {
    drug1Name: '华法林',
    drug2Name: '阿莫西林',
    interactionType: '药效增强',
    severity: 'medium',
    description: '阿莫西林可能增强华法林的抗凝作用，增加出血风险',
    recommendation: '联用期间需密切监测INR值，必要时调整华法林剂量',
    source: 'database',
  },
  {
    drug1Name: '华法林',
    drug2Name: '奥美拉唑',
    interactionType: '药效增强',
    severity: 'medium',
    description: '奥美拉唑可能抑制华法林代谢，增强抗凝作用',
    recommendation: '联用时需监测INR值，必要时调整华法林剂量',
    source: 'database',
  },
  {
    drug1Name: '二甲双胍',
    drug2Name: '格列美脲',
    interactionType: '药效增强',
    severity: 'medium',
    description: '两种降糖药联用可能增加低血糖风险',
    recommendation: '联用时需监测血糖，注意低血糖症状',
    source: 'database',
  },
  {
    drug1Name: '氨氯地平',
    drug2Name: '辛伐他汀',
    interactionType: '药效增强',
    severity: 'medium',
    description: '氨氯地平可能增加辛伐他汀的血药浓度，增加肌病风险',
    recommendation: '辛伐他汀剂量不应超过20mg/日，注意肌肉疼痛症状',
    source: 'database',
  },
  {
    drug1Name: '美托洛尔',
    drug2Name: '硝苯地平',
    interactionType: '药效增强',
    severity: 'medium',
    description: '两种降压药联用可能导致血压过度降低和心动过缓',
    recommendation: '联用时需监测血压和心率，从小剂量开始',
    source: 'database',
  },
  {
    drug1Name: '地西泮',
    drug2Name: '奥美拉唑',
    interactionType: '药效增强',
    severity: 'low',
    description: '奥美拉唑可能抑制地西泮代谢，延长其作用时间',
    recommendation: '联用时注意观察镇静作用是否增强',
    source: 'database',
  },
  {
    drug1Name: '氯雷他定',
    drug2Name: '西替利嗪',
    interactionType: '药效增强',
    severity: 'low',
    description: '两种抗组胺药联用可能增加镇静作用',
    recommendation: '一般不建议联用，选择其中一种即可',
    source: 'database',
  },
  {
    drug1Name: '阿莫西林',
    drug2Name: '头孢克肟',
    interactionType: '无显著相互作用',
    severity: 'low',
    description: '两种抗生素作用机制相似，但无明显相互作用',
    recommendation: '一般不需要联用，选择其中一种即可',
    source: 'database',
  },
  {
    drug1Name: '对乙酰氨基酚',
    drug2Name: '华法林',
    interactionType: '药效增强',
    severity: 'medium',
    description: '长期大剂量使用对乙酰氨基酚可能增强华法林的抗凝作用',
    recommendation: '短期小剂量使用相对安全，长期使用需监测INR值',
    source: 'database',
  },
  {
    drug1Name: '阿托伐他汀',
    drug2Name: '氨氯地平',
    interactionType: '药效增强',
    severity: 'low',
    description: '氨氯地平可能轻度增加阿托伐他汀的血药浓度',
    recommendation: '联用相对安全，注意监测肝功能和肌酶',
    source: 'database',
  },
  {
    drug1Name: '雷尼替丁',
    drug2Name: '华法林',
    interactionType: '药效增强',
    severity: 'low',
    description: '雷尼替丁可能轻度增强华法林的抗凝作用',
    recommendation: '联用时注意监测INR值',
    source: 'database',
  },
  {
    drug1Name: '艾司唑仑',
    drug2Name: '地西泮',
    interactionType: '药效增强',
    severity: 'medium',
    description: '两种苯二氮䓬类药物联用会增强镇静作用和依赖风险',
    recommendation: '不建议联用，选择其中一种即可',
    source: 'database',
  },
]
